name: Feature request
description: 機能の追加や改善に関する要望を記載するテンプレートです。
labels: [Feature request]
body:
  - type: textarea
    attributes:
      label: 機能要望
      description: 要望をできるだけ詳しく記載してください。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 課題背景
      description: なぜその機能が必要なのか教えてください。
  - type: input
    attributes:
      label: 関連課題
      description: 関連するIssueを既に認知している場合は教えてください。